Fix extra action called to supplelement with DS
kazu-yamamoto/dnsext pull request #127
Opened 2023-07-13 07:15 UTC by khibino

Fix conditions under which DS supplementing action is called

There are two cases in which the delegation information needs to be supplemented with DS

- When the delegation information is configured from the cache, but there is no cache of DS.
- When the child zones share the same authoritative server and the delegation information that should be available cannot be obtained.

Fixes a problem where the DS supplementing action is called in cases other than the above two cases.

This should fix #126.

no `fill delegation` line for "www.mew.org." example

```
...
delegation - verification success - RRSIG of DS: "." -> "org."
...
delegation - no DS, so no verify: "org." -> "mew.org."
...
no verification - no DS, "www.mew.org." A
;; 52usec

;; HEADER SECTION:
;Standard query, NoError, id: 0
;Flags: Recursion Desired, Recursion Available

;; QUESTION SECTION:
;www.mew.org.		IN	A

;; ANSWER SECTION:
www.mew.org.	3600(1 hour)	IN	A	202.238.220.92

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:
```

2023-07-13 09:21 UTC, kazu-yamamoto requested changes
Could you add test cases?

2023-07-14 11:46 UTC, khibino commented
Add test cases to confirm fill-action result and to confirm fill-action called or not called.
https://github.com/kazu-yamamoto/dnsext/pull/127/commits/9249953e5ffd9d4ed9586e6857ac360b3f111fdb
https://github.com/kazu-yamamoto/dnsext/pull/127/commits/841653fccd2bb7be395af8c553270c1aaed36975

2023-07-14 16:43 UTC, khibino commented
Fixed doctest output mismatch due to incomplete-uni-patterns warning.
https://github.com/kazu-yamamoto/dnsext/pull/127/commits/a0316efd0cd17c561456f8430be59a6b91c5bb66

2023-07-18 00:49 UTC, merged

2023-07-18 00:50 UTC, kazu-yamamoto commented
Merged.